import type { DateIdea } from '../services/DateIdeasService';
import React, { useEffect, useMemo, useState, useCallback } from 'react';
import { ScrollView, View, TouchableOpacity, StyleSheet, Linking, ActivityIndicator, RefreshControl } from 'react-native';
import SmartList from '../ui/components/SmartList';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import type { StackScreenProps } from '@react-navigation/stack';

import type { RootStackParamList } from '../navigation/types';
import Screen from '../ui/components/Screen';
import Header from '../ui/components/Header';
import Card from '../ui/components/Card';
import AppText from '../ui/components/AppText';
import Button from '../ui/components/Button';
import { useAppTheme } from '../ui/theme/ThemeProvider';
import { haptics } from '../ui/haptics';
import { getSnapshot, findFreeSlot } from '../services/SnapshotService';
import { generate, getPlacesCategory } from '../services/DateIdeasService';
import GooglePlacesService from '../services/GooglePlacesService';
import type { PlaceResult } from '../services/GooglePlacesService';
import CalendarService from '../services/CalendarService';
import { getFirstName } from '../utils/partners';

// ─── Constants ─────────────────────────────────────────────

const VIBES = [
  { id: 'all', label: 'All', icon: 'shuffle' },
  { id: 'romantic', label: 'Romantic', icon: 'heart' },
  { id: 'cozy', label: 'Cozy', icon: 'coffee' },
  { id: 'playful', label: 'Playful', icon: 'smile' },
  { id: 'adventurous', label: 'Adventure', icon: 'compass' },
  { id: 'thoughtful', label: 'Thoughtful', icon: 'book' },
];

const PRICE_LABELS = { 0: 'Free', 1: '$', 2: '$$', 3: '$$$', 4: '$$$$' };

function formatSlot(slot) {
  if (!slot) return null;
  try {
    const d = new Date(slot.date + 'T00:00:00');
    const day = d.toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' });
    return `${day} at ${slot.time}`;
  } catch {
    return `${slot.date} ${slot.time}`;
  }
}

function starString(rating) {
  const full = Math.floor(rating);
  const half = rating - full >= 0.5;
  return '\u2605'.repeat(full) + (half ? '\u00BD' : '');
}

// ─── Components ────────────────────────────────────────────

function VibeChip({ item, active, theme, onPress }) {
  return (
    <TouchableOpacity
      accessibilityRole="button"
      onPress={onPress}
      activeOpacity={0.8}
      style={[
        st.chip,
        {
          backgroundColor: active ? theme.accent.primary : theme.bg.muted,
          borderColor: active ? theme.accent.primary : theme.divider,
          borderWidth: StyleSheet.hairlineWidth,
        },
      ]}
    >
      <Feather name={item.icon} size={12} color={active ? theme.text.inverse : theme.text.secondary} />
      <AppText style={[st.chipLabel, { color: active ? theme.text.inverse : theme.text.secondary }]}>{item.label}</AppText>
    </TouchableOpacity>
  );
}

function IdeaCard({ idea, slot, partner, theme, navigation, expanded, onToggle, nearbyPlaces, loadingPlaces, onFindSlot, onRetryPlaces, onEnableVenues, onGoAtHome }) {
  const placesCat = getPlacesCategory(idea);
  const isHome = !placesCat;

  const book = async () => {
    if (!slot || !partner) return;
    const ev = await CalendarService.addEvent({
      title: idea.title,
      date: slot.date,
      time: slot.time,
      durationMinutes: idea.durationMins || 90,
      description: 'Generated by U&Me \u2014 Tonight suggestion',
      sharedWith: [partner.id],
      color: theme.accent.primary,
    });
    haptics.success();
    navigation.navigate('EventDetails', { event: ev });
  };

  const openMaps = (place: PlaceResult) => {
    const url = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place.name)}&query_place_id=${place.placeId}`;
    Linking.openURL(url).catch(() => {});
  };

  return (
    <Card style={st.ideaCard}>
      <TouchableOpacity
              accessibilityRole="button" activeOpacity={0.9} onPress={onToggle}>
        <View style={st.ideaHeader}>
          <View style={[st.vibeTag, { backgroundColor: theme.accent.primary + '15' }]}>
            <AppText style={[st.vibeTagText, { color: theme.accent.primary }]}>{idea.vibe}</AppText>
          </View>
          {isHome && (
            <View style={[st.vibeTag, { backgroundColor: theme.bg.muted, marginLeft: 6 }]}>
              <AppText style={[st.vibeTagText, { color: theme.text.tertiary }]}>at home</AppText>
            </View>
          )}
          <View style={st.spacer} />
          <AppText variant="caption" color="tertiary">~{idea.durationMins || 90}m</AppText>
          <Feather name={expanded ? 'chevron-up' : 'chevron-down'} size={16} color={theme.text.tertiary} style={st.ml6} />
        </View>

        <AppText numberOfLines={2} style={[st.ideaTitle, { color: theme.text.primary }]}>{idea.title}</AppText>
        <AppText variant="bodySm" color="secondary" style={st.mt4} numberOfLines={expanded ? undefined : 2}>{idea.details}</AppText>
      </TouchableOpacity>

      {expanded && (
        <View style={st.expandedWrap}>
          {/* Free slot */}
          <View style={[st.slotRow, { backgroundColor: theme.bg.subtle, borderColor: theme.divider }]}>
            <Feather name="clock" size={14} color={theme.text.tertiary} />
            <AppText variant="bodySm" color="secondary" style={{ marginLeft: 8, flex: 1 }}>
              {slot ? `Best slot: ${formatSlot(slot)}` : 'No free slot found in the next 2 days'}
            </AppText>
          </View>

          {(idea.why || (idea.firstSteps && idea.firstSteps.length > 0)) && (
            <View style={st.whyWrap}>
              {idea.why ? (
                <View style={st.whyBlock}>
                  <AppText variant="caption" color="tertiary" style={st.sectionLabel}>WHY IT'S GOOD</AppText>
                  <AppText variant="bodySm" color="secondary" style={st.mt6}>{idea.why}</AppText>
                </View>
              ) : null}

              {idea.firstSteps && idea.firstSteps.length > 0 ? (
                <View style={st.whyBlock}>
                  <AppText variant="caption" color="tertiary" style={st.sectionLabel}>WHAT TO DO FIRST</AppText>
                  {idea.firstSteps.slice(0, 5).map((s: string, idx: number) => (
                    <View key={`${idx}-${s}`} style={st.stepRow}>
                      <View style={[st.dot, { backgroundColor: theme.accent.primary }]} />
                      <AppText variant="bodySm" color="secondary" style={st.stepText}>{s}</AppText>
                    </View>
                  ))}
                </View>
              ) : null}
            </View>
          )}

          {!slot && (
            <View style={st.noSlotActions}>
              <TouchableOpacity
              accessibilityRole="button"
                style={[st.actionPill, { backgroundColor: theme.bg.muted, borderColor: theme.divider }]}
                onPress={() => onFindSlot && onFindSlot({ days: 7 })}
              
          activeOpacity={0.8}
        >
                <Feather name="calendar" size={14} color={theme.text.secondary} />
                <AppText variant="bodySm" color="secondary" style={st.ml8}>Expand to 7 days</AppText>
              </TouchableOpacity>

              <TouchableOpacity
              accessibilityRole="button"
                style={[st.actionPill, { backgroundColor: theme.bg.muted, borderColor: theme.divider }]}
                onPress={() => onFindSlot && onFindSlot({ durationMins: 60 })}
              
          activeOpacity={0.8}
        >
                <Feather name="clock" size={14} color={theme.text.secondary} />
                <AppText variant="bodySm" color="secondary" style={st.ml8}>Try 60 min</AppText>
              </TouchableOpacity>

              <TouchableOpacity
              accessibilityRole="button"
                style={[st.actionPill, { backgroundColor: theme.bg.muted, borderColor: theme.divider }]}
                onPress={() => onGoAtHome && onGoAtHome()}
              
          activeOpacity={0.8}
        >
                <Feather name="home" size={14} color={theme.text.secondary} />
                <AppText variant="bodySm" color="secondary" style={st.ml8}>At-home idea</AppText>
              </TouchableOpacity>
            </View>
          )}

          {/* Nearby places */}
          {!isHome && (
            <View style={st.mt10}>
              <View style={st.nearbyHeader}>
                <Feather name="map-pin" size={12} color={theme.text.tertiary} />
                <AppText variant="caption" color="tertiary" style={{ marginLeft: 6, letterSpacing: 0.3 }}>NEARBY VENUES</AppText>
              </View>

              <View style={[st.venueStatus, { backgroundColor: theme.bg.subtle, borderColor: theme.divider }]}>
                <Feather
                  name={GooglePlacesService.isConfigured()
                    ? (nearbyPlaces.length >= 3 ? 'check-circle' : nearbyPlaces.length >= 1 ? 'info' : 'alert-circle')
                    : 'slash'}
                  size={14}
                  color={GooglePlacesService.isConfigured()
                    ? (nearbyPlaces.length >= 3 ? theme.accent.primary : theme.text.tertiary)
                    : theme.text.tertiary}
                />
                <AppText variant="bodySm" color="secondary" style={{ marginLeft: 8, flex: 1 }}>
                  {GooglePlacesService.isConfigured()
                    ? (nearbyPlaces.length >= 3
                        ? 'High confidence venues nearby'
                        : nearbyPlaces.length >= 1
                          ? 'Some venues found — refresh for more'
                          : 'Low confidence — try a wider radius')
                    : 'Venues are off — add a Places API key'}
                </AppText>

                {!GooglePlacesService.isConfigured() && (
                  <TouchableOpacity
              accessibilityRole="button" onPress={() => onEnableVenues && onEnableVenues()}
          activeOpacity={0.8}
        >
                    <AppText variant="bodySm" style={{ color: theme.accent.primary, fontWeight: '700' }}>Enable</AppText>
                  </TouchableOpacity>
                )}

                {GooglePlacesService.isConfigured() && nearbyPlaces.length === 0 && (
                  <TouchableOpacity
              accessibilityRole="button" onPress={() => onRetryPlaces && onRetryPlaces(placesCat, 10000)}
          activeOpacity={0.8}
        >
                    <AppText variant="bodySm" style={{ color: theme.accent.primary, fontWeight: '700' }}>Wider</AppText>
                  </TouchableOpacity>
                )}
              </View>


              {loadingPlaces && (
                <View style={{ paddingVertical: 12, alignItems: 'center' }}>
                  <ActivityIndicator size="small" color={theme.accent.primary} />
                </View>
              )}

              {!loadingPlaces && nearbyPlaces.length === 0 && (
                <AppText variant="caption" color="tertiary" style={{ paddingVertical: 8, fontStyle: 'italic' }}>
                  {GooglePlacesService.isConfigured()
                    ? 'No highly-rated places found nearby'
                    : 'Add a Google Places API key to see nearby venues'}
                </AppText>
              )}

              {nearbyPlaces.map((place: PlaceResult) => (
                <TouchableOpacity
              accessibilityRole="button"
                  key={place.placeId}
                  onPress={() => openMaps(place)}
                  activeOpacity={0.8}
                  style={[st.placeRow, { backgroundColor: theme.bg.subtle, borderColor: theme.divider }]}
                >
                  <View style={st.flex1}>
                    <AppText variant="body" style={{ fontWeight: '600' }}>{place.name}</AppText>
                    <AppText variant="caption" color="secondary" numberOfLines={1}>{place.vicinity}</AppText>
                    <View style={st.placeMetaRow}>
                      <AppText variant="caption" style={{ color: theme.accent.primary }}>
                        {starString(place.rating)} {place.rating}
                      </AppText>
                      <AppText variant="caption" color="tertiary" style={st.ml8}>
                        ({place.userRatingsTotal})
                      </AppText>
                      {place.priceLevel != null && (
                        <AppText variant="caption" color="tertiary" style={st.ml8}>
                          {PRICE_LABELS[place.priceLevel] || ''}
                        </AppText>
                      )}
                      {place.openNow === true && (
                        <View style={[st.openBadge, { backgroundColor: theme.success + '20' }]}>
                          <AppText style={{ fontSize: 10, fontWeight: '600', color: theme.success }}>Open</AppText>
                        </View>
                      )}
                    </View>
                  </View>
                  <Feather name="external-link" size={14} color={theme.text.tertiary} style={st.ml8} />
                </TouchableOpacity>
              ))}
            </View>
          )}

          {/* Actions */}
          <View style={st.expandedWrap}>
            <Button
              size="lg"
              title={slot ? 'Add to calendar' : 'Find a slot'}
              onPress={slot ? book : () => navigation.navigate('AutoSchedule')}
            />
          </View>
        </View>
      )}
    </Card>
  );
}

const MemoIdeaCard = React.memo(IdeaCard);
MemoIdeaCard.displayName = 'IdeaCard';

// ─── Main Screen ───────────────────────────────────────────

type Props = StackScreenProps<RootStackParamList, 'TonightSuggestion'>;

export default function TonightSuggestionScreen({ navigation }: Props) {
  const { theme } = useAppTheme();
  const [engine, setEngine] = useState<Record<string, unknown> | null>(null);
  const [slot, setSlot] = useState<Record<string, unknown> | null>(null);
  const [slotDays, setSlotDays] = useState(2);
  const [slotDurationMins, setSlotDurationMins] = useState(90);
  const [atHomeMode, setAtHomeMode] = useState(false);
  const [vibe, setVibe] = useState('all');
  const [expandedIdx, setExpandedIdx] = useState(0);
  const [nearbyCache, setNearbyCache] = useState({});
  const [loadingPlaces, setLoadingPlaces] = useState({});
  const [refreshing, setRefreshing] = useState(false);

  const refreshSlot = useCallback(async (overrides = {}) => {
    const days = overrides.days ?? slotDays;
    const durationMins = overrides.durationMins ?? slotDurationMins;
    setSlotDays(days);
    setSlotDurationMins(durationMins);
    const s = await findFreeSlot({ days, durationMins, startHour: 18, endHour: 22 });
    setSlot(s);
    return s;
  }, [slotDays, slotDurationMins]);

  const load = useCallback(async () => {
    const snap = await getSnapshot({ days: 7 });
    setEngine(snap);
    await refreshSlot();
    setNearbyCache({});
    setLoadingPlaces({});
  }, [refreshSlot]);

  useEffect(() => { load(); }, [load]);

  const retryPlaces = useCallback((category, radiusM = 10000) => {
    if (!category) return;
    setLoadingPlaces((prev) => ({ ...prev, [category]: true }));
    GooglePlacesService.searchNearby({ category, radiusM, maxResults: 5, minRating: 3.5 })
      .then((places: PlaceResult[]) => {
        setNearbyCache((prev) => ({ ...prev, [category]: places || [] }));
      })
      .finally(() => {
        setLoadingPlaces((prev) => ({ ...prev, [category]: false }));
      });
  }, []);

  const enableVenues = useCallback(() => {
    // Send them to where they can add the key (or paste EXPO_PUBLIC_GOOGLE_PLACES_API_KEY).
    navigation.navigate('AutopilotSetup');
  }, [navigation]);

  const goAtHome = useCallback(() => {
    setAtHomeMode(true);
    setVibe('all');
    setExpandedIdx(0);
    haptics.light();
  }, []);


  const autoVibe = useMemo(() => {
    const pct = Math.round((engine?.balance || 0.5) * 100);
    if (pct < 60) return 'cozy';
    if (pct < 75) return 'romantic';
    return 'playful';
  }, [engine]);

  const effectiveVibe = vibe === 'all' ? null : vibe;
  const ideas = useMemo(() => {
    const generated = generate({
      vibe: effectiveVibe || autoVibe,
      budget: 'mid',
      time: 'tonight',
      count: 8,
    });
    if (!atHomeMode) return generated;
    const home = generated.filter((i: DateIdea) => !getPlacesCategory(i));
    return home.length ? home : generated;
  }, [effectiveVibe, autoVibe, atHomeMode]);

  // Load nearby places when an idea is expanded
  useEffect(() => {
    if (expandedIdx == null || !ideas[expandedIdx]) return;
    const idea = ideas[expandedIdx];
    const cat = getPlacesCategory(idea);
    if (!cat) return;
    if (nearbyCache[cat]) return;

    let alive = true;
    setLoadingPlaces((prev) => ({ ...prev, [cat]: true }));

    GooglePlacesService.searchNearby({ category: cat, radiusM: 5000, maxResults: 5, minRating: 3.5 })
      .then((places: PlaceResult[]) => {
        if (!alive) return;
        setNearbyCache((prev) => ({ ...prev, [cat]: places }));
      })
      .catch(() => {
        if (!alive) return;
        setNearbyCache((prev) => ({ ...prev, [cat]: [] }));
      })
      .finally(() => {
        if (!alive) return;
        setLoadingPlaces((prev) => ({ ...prev, [cat]: false }));
      });

    return () => { alive = false; };
  }, [expandedIdx, ideas]);

  const partner = engine?.partner;
  const partnerName = getFirstName(partner?.name, 'Partner');

  const insets = useSafeAreaInsets();

  // Build flat list data
  const listData = useMemo(() => {
    const items = [];
    items.push({ type: 'intro', key: 'intro' });
    items.push({ type: 'vibes', key: 'vibes' });
    ideas.forEach((idea, idx) => items.push({ type: 'idea', key: `idea_${idx}`, idea, idx }));
    if (engine?.tension?.[0]) items.push({ type: 'nudge', key: 'nudge', data: engine.tension[0] });
    items.push({ type: 'footer', key: 'footer' });
    return items;
  }, [ideas, engine]);

  const renderItem = useCallback(({ item }) => {
    switch (item.type) {
      case 'intro':
        return (
          <Card>
            <AppText style={[st.cardTitle, { color: theme.text.primary }]}>A small win for tonight</AppText>
            <AppText variant="bodySm" color="secondary" style={st.mt4}>
              {partner ? `Matched to your rhythm with ${partnerName}` : 'Ideas matched to your current mood'} — pick one, tweak it, or refresh.
            </AppText>
          </Card>
        );
      case 'vibes':
        return (
          <ScrollView horizontal nestedScrollEnabled showsHorizontalScrollIndicator={false} contentContainerStyle={st.vibeRow}>
            {VIBES.map((v) => (
              <VibeChip key={v.id} item={v} active={vibe === v.id} theme={theme}
                onPress={() => { haptics.light(); setVibe(v.id); setExpandedIdx(0); }} />
            ))}
          </ScrollView>
        );
      case 'idea': {
        const cat = getPlacesCategory(item.idea);
        const places = cat ? (nearbyCache[cat] || []) : [];
        const isLoading = cat ? !!loadingPlaces[cat] : false;
        const onToggle = () => {
          haptics.light();
          setExpandedIdx((prev) => (prev === item.idx ? null : item.idx));
        };
        return (
          <MemoIdeaCard
            idea={item.idea}
            slot={slot}
            partner={partner}
            theme={theme}
            navigation={navigation}
            expanded={expandedIdx === item.idx}
            onToggle={onToggle}
            nearbyPlaces={places}
            loadingPlaces={isLoading}
            onFindSlot={refreshSlot}
            onRetryPlaces={retryPlaces}
            onEnableVenues={enableVenues}
            onGoAtHome={goAtHome}
          />
        );
      }
      case 'nudge':
        return (
          <Card style={st.mt16}>
            <View style={st.nudgeHeader}>
              <Feather name="heart" size={14} color={theme.accent.primary} />
              <AppText variant="caption" color="tertiary" style={{ marginLeft: 6, letterSpacing: 0.5 }}>GENTLE NUDGE</AppText>
            </View>
            <AppText variant="body" style={{ fontWeight: '600', marginTop: 6 }}>{item.data.title}</AppText>
            <AppText variant="bodySm" color="secondary" style={st.mt4}>{item.data.body}</AppText>
          </Card>
        );
      case 'footer':
        return (
          <View style={st.mt16}>
            <Button
              variant="secondary"
              title="Open Date Suggestions"
              size="lg"
              onPress={() => navigation.navigate('DateGenerator', { time: 'tonight' })}
            />
          </View>
        );
      default: return null;
    }
  }, [theme, vibe, expandedIdx, slot, partner, partnerName, nearbyCache, loadingPlaces,
      navigation, refreshSlot, retryPlaces, enableVenues, goAtHome]);

  return (
    <Screen>
      <Header
        title="Tonight"
        leftAction={{ icon: 'arrow-left', label: 'Back', onPress: () => navigation.goBack() }}
        rightAction={{ icon: 'refresh-cw', onPress: () => { haptics.light(); load(); } }}
      />
      <SmartList style={{ flex: 1 }} nestedScrollEnabled keyboardDismissMode="on-drag" keyboardShouldPersistTaps="handled"
        data={listData}
        keyExtractor={(item) => item.key}
        estimatedItemSize={160}
        renderItem={renderItem}
        contentContainerStyle={{ flexGrow: 1, padding: 16, paddingBottom: Math.max(insets.bottom, 32) + 160 }}
        showsVerticalScrollIndicator={false}
        removeClippedSubviews={false}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async () => { setRefreshing(true); await load(); setRefreshing(false); }} tintColor={theme.accent.primary} />}
      />
    </Screen>
  );
}

// ─── Styles ────────────────────────────────────────────────

const st = StyleSheet.create({
  vibeRow: { flexDirection: 'row', gap: 8, paddingVertical: 12 },
  chip: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999 },
  chipLabel: { fontSize: 12, fontWeight: '600', marginLeft: 5 },
  cardTitle: { fontSize: 18, fontWeight: '800' },
  ideaHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  vibeTag: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  vibeTagText: { fontSize: 11, fontWeight: '600', textTransform: 'capitalize' },
  ideaTitle: { fontSize: 16, fontWeight: '700', lineHeight: 22 },
  slotRow: { flexDirection: 'row', alignItems: 'center', padding: 10, borderRadius: 10, borderWidth: StyleSheet.hairlineWidth },
  noSlotActions: { marginTop: 10, gap: 12 },
  actionPill: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 10, borderRadius: 12, borderWidth: StyleSheet.hairlineWidth },
  venueStatus: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 10, borderRadius: 12, borderWidth: StyleSheet.hairlineWidth, marginTop: 10 },
  whyWrap: { marginTop: 12, gap: 10 },
  whyBlock: { padding: 12, borderRadius: 12, borderWidth: StyleSheet.hairlineWidth },
  sectionLabel: { letterSpacing: 0.6 },
  stepRow: { flexDirection: 'row', alignItems: 'flex-start', marginTop: 6 },
  dot: { width: 6, height: 6, borderRadius: 999, marginTop: 6, marginRight: 10 },
  stepText: { flex: 1 },

  nearbyHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  placeRow: { flexDirection: 'row', alignItems: 'center', padding: 12, borderRadius: 10, borderWidth: StyleSheet.hairlineWidth, marginTop: 6 },
  placeMetaRow: { flexDirection: 'row', alignItems: 'center', marginTop: 3 },
  openBadge: { marginLeft: 8, paddingHorizontal: 8, paddingVertical: 2, borderRadius: 4 },
  nudgeHeader: { flexDirection: 'row', alignItems: 'center' },
  spacer: { flex: 1 },
  expandedWrap: { marginTop: 14 },
  flex1: { flex: 1 },
  ml6: { marginLeft: 6 },
  ml8: { marginLeft: 8 },
  mt10: { marginTop: 10 },
  mt16: { marginTop: 16 },
  mt4: { marginTop: 4 },
  mt6: { marginTop: 6 },
  ideaCard: { marginTop: 14 },
});
